### ISSUE TITLE
ldap.schema.subentry.SubSchema broken in Python 3

### ISSUE THREAD

**Issue by HonzaCholasta** [pyldap/pyldap#11]
The SubSchema class constructor expects a dictionary returned by LDAP search as its first argument. With Python 3, attribute values in the dictionary are bytes, but the SubSchema class expects str, and thus fails to parse the dictionary.

**Comment by HonzaCholasta** [comment]
Reproducer:

``` python
import ldap
c = ldap.initialize('ldap://example.com')
c.simple_bind_s('cn=user', 'password')
r = c.search_s('cn=schema', ldap.SCOPE_BASE, attrlist=['attributeTypes', 'objectClasses'])
s = ldap.schema.SubSchema(r[0][1])
```

The last statement should succeed.

**Comment by msrb** [comment]
I was trying to reproduce this issue, but I wasn't successful. The chances are that I was doing something wrong, since I am no LDAP expert. Could you please confirm that the problem still exists in current master branch? If so, could you please paste stacktrace (or input which causes trouble in SubSchema constructor) here?

This is a long shot, but [README](https://github.com/pyldap/pyldap/blob/master/README#L43) recommends calling `ldap.initialize()` with `bytes_mode=False`.

**Comment by HonzaCholasta** [comment]
This is what I'm getting on Fedora 22 with python3-pyldap from the rkuska/ipa_python3 COPR, using FreeIPA's public demo server:

```
$ python3
Python 3.4.2 (default, Jul  9 2015, 17:24:30) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ldap
>>> c = ldap.initialize('ldap://ipa.demo1.freeipa.org')
>>> c.simple_bind_s('uid=admin,cn=users,cn=accounts,dc=demo1,dc=freeipa,dc=org', 'Secret123')
(97, [], 1, [])
>>> r = c.search_s('cn=schema', ldap.SCOPE_BASE, attrlist=['attributeTypes', 'objectClasses'])
>>> s = ldap.schema.SubSchema(r[0][1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.4/site-packages/ldap/schema/subentry.py", line 100, in __init__
    se_instance = se_class(attr_value)
  File "/usr/lib64/python3.4/site-packages/ldap/schema/models.py", line 52, in __init__
    self.set_id(l[1])
IndexError: list index out of range
```
