### ISSUE TITLE
_ldap_call cannot handle unicode in modlist.

### ISSUE THREAD

**Issue by Firstyear** [pyldap/pyldap#35]
This dict: 

{'ReplicaLegacyConsumer': 'off', 'suffix': u'dc=example,dc=com', 'ReplicaFlags': '1', 'Replicaid': '1', 'ReplicaBindDN': 'cn=replrepl,cn=config', 'ReplicaType': '3'}

Is converted to a modlist, and then given to py.ldap. This causes the following exception. 

``` python
    def _ldap_call(self,func,*args,**kwargs):
      """
        Wrapper method mainly for serializing calls into OpenLDAP libs
        and trace logs
        """
      self._ldap_object_lock.acquire()
      if __debug__:
        if self._trace_level>=1:
          self._trace_file.write('*** %s %s - %s\n%s\n' % (
            repr(self),
            self._uri,
            '.'.join((self.__class__.__name__,func.__name__)),
            pprint.pformat((args,kwargs))
          ))
          if self._trace_level>=9:
            traceback.print_stack(limit=self._trace_stack_limit,file=self._trace_file)
      diagnostic_message_success = None
      try:
        try:
>         result = func(*args,**kwargs)
E         TypeError: ('expected a string in the list', u'dc=example,dc=com')
```

**Comment by rbarrois** [comment]
Well, in Py3-compatible mode, a modlist is expected to be a list of either (op_int, attr_text, value_bytes) or (attr_text, value_bytes).

pyldap enforces the "values as bytes" to prevent you from nasty bugs further on.

Your example only shows `_ldap_call`, which is the wrapper for the C API; which method did you use that called into that function?

Thanks!

**Comment by Firstyear** [comment]
It was a modify_s() call. There was a modlist built out of the dictionary attached. Specifically, it had issues with the (ldap.MOD_ADD, 'nsds5replicaroot', [u'dc=example,dc=com'])

**Comment by rbarrois** [comment]
`pyldap` has no knowledge of the underlying LDAP schema.

As such, it cannot guess whether a value is binary (e.g a photo) or text.
For this reason, _all_ values must be encoded to bytes beforehand.

In your case, you should end up with `(ldap.MOD_ADD, u'nsds5replicaroot', [b'dc=example,dc=com'])`.

**Comment by rbarrois** [comment]
@Firstyear have you had a chance to look into this?

**Comment by Firstyear** [comment]
Sorry I have not. 

I think this asks the question, do we expect the user to hand in byte types? Or do we want the library to automatically cast?

**Comment by rbarrois** [comment]
This is one explicit choice done by both python-ldap and pyldap: values are always bytes.

The main difference is that python-ldap expects bytes for keys and dns which are mandated by the LDAP specifications to be UTF-8; pyldap uses text since there is no risk of breakage there.

For instance:
- In an ActiveDirectory setup, the `userAccountControl` field is a bitmask
- Other schemas may store pictures in an LDAP value.

The only way I can think of where a LDAP library should accept text as values and cast them would be if that library were to master the underlying LDAP schema, thus knowing what the expected values would be for each field.

For your specific case, the best would be to handle the "cast to bytes" in the "dict to modlist" conversion function.

Feel free to reopen this issue if that doesn't work for you :)

**Comment by ethankleinman** [comment]
Does `pyldap` expect the parameter `cred` in `simple_bind_s()` to also be bytes?
@rbarrois
