### ISSUE TITLE
LDAP <> Python Types

### ISSUE THREAD

**Issue by wyc** [pyldap/pyldap#43]
I was wondering if it would be useful to map Python types to the existing LDAP types. Right now it seems that every value is a bytestring. The `ldap3` library does this. I'm willing to implement this for `pyldap`. Should we investigate it further?

**Comment by encukou** [comment]
Hello,
There would be many hard corner cases involved in that effort. Mapping to the correct types implies knowing the schema, which is not always available, and when available it's not always complete or entirely correct. The Python types involved are not always clear. (What do you map jpegPhoto to? A [Pillow](https://python-pillow.org/) image?)
Due to the number of such decisions, this is better left to a higher-level library built on top of `pyldap`. (I worked on one such library: [ipaldap](https://github.com/encukou/freeipa/blob/master/ipapython/ipaldap.py), which could likely be extracted from the FreeIPA framework. Another library that does this is [web2ldap](https://web2ldap.de/) by Michael Ströder, author of `python-ldap`.)

**Comment by wyc** [comment]
Make sense. Thanks!
