### ISSUE TITLE
Windows Installation Issue

### ISSUE THREAD

**Issue by msbohannon** [pyldap/pyldap#67]
I am getting an error when I try install (e.g. pip install pyldap).  The error is:
 
c:\users\<user-name>\appdata\local\temp\pip-build-mek8zven\pyldap\modules\errors.h(8): fatal error C1083: Cannot open include file: 'lber.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

From what I can tell, I believe this is related to an openldap library but I do not know how to resolve.

Any help would be very much appreciated.  Thanks.

**Comment by tiran** [comment]
You need to install the OpenLDAP client libraries and header files on your system. I don't know if Windows is supported at all. Good luck!

**Comment by chrisheckey** [comment]
I would just use Gohlke's wheels:
http://www.lfd.uci.edu/~gohlke/pythonlibs/#pyldap

**Comment by rbarrois** [comment]
For installation on Windows, you should follow the upstream python-ldap installation instructions:
https://www.python-ldap.org/doc/html/installing.html

Since this project is just a Python3-compatible fork of python-ldap, topics related to the core of python-ldap should be reported to its official support channel, the python-ldap@python.org mailing list.

**Comment by seanvree** [comment]
I can't get this to work.  Any updates to this

**Comment by iPurpl3x** [comment]
I would appreciate updates too. I'm stuck on this for a day now.

**Comment by rbarrois** [comment]
@seanvree @iPurpl3x As stated above, this project adds a Python3 compatibility layer on top of the upstream python-ldap project.

Obviously, if you're able to install python-ldap but get a failure on pyldap, then the issue is on pyldap side, and this is the right place to ask — please reopen the issue with all details in that case.

However, if you can't get python-ldap installed either, the best course of action would be to ask for help on the python-ldap@python.org mailing list.

Thanks, and good luck :)

**Comment by RakeshNagarajan** [comment]
I am also facing the same issues

**Comment by rbarrois** [comment]
@RakeshNagarajan pyldap has been merged back into the upstream python-ldap.
I strongly advise AGAINST using pyldap any longer.
Any python-ldap version from 3.0 onwards is based on the pyldap codebase.
